import { col, type ModulePageDef } from "./types";

const STATUS = ["Active", "Inactive", "Pending", "Suspended"];
const LEAD_STATUS = ["New", "Contacted", "Demo Scheduled", "Demo Completed", "Won", "Lost"];
const ONBOARDING = [
  "NEW_LEAD",
  "CONTACTED",
  "DEMO_SCHEDULED",
  "TRIAL_ACTIVE",
  "PAYMENT_PENDING",
  "SUBSCRIPTION_ACTIVE",
  "LIVE",
  "SUSPENDED",
];

export const MODULES: ModulePageDef[] = [
  /* ------------------------------ Super Admin ----------------------------- */
  {
    path: "platform/organization-types",
    title: "Organization Types",
    description: "Clinic, pharmacy, laboratory and diagnostic centre categories.",
    group: "platform",
    singular: "Organization Type",
    columns: [
      col("name", "Type Name", "text", { required: true }),
      col("code", "Code", "code", { required: true }),
      col("modules", "Default Modules", "text", { secondary: true }),
      col("organizations", "Organizations", "number"),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "platform/organizations",
    title: "Organizations",
    description: "Every tenant on the MediUnivers platform.",
    group: "platform",
    singular: "Organization",
    rowCount: 64,
    stats: [
      { label: "Total organizations", value: "482", delta: "+8.2%", trend: "up" },
      { label: "Live", value: "371", delta: "+3.1%", trend: "up" },
      { label: "On trial", value: "64", delta: "-1.4%", trend: "down" },
      { label: "Suspended", value: "12", delta: "+2", trend: "up" },
    ],
    columns: [
      col("name", "Organization", "org", { required: true }),
      col("type", "Type", "badge", {
        options: ["Clinic", "Pharmacy", "Laboratory", "Multi-Clinic"],
      }),
      col("owner", "Owner", "name"),
      col("email", "Email", "email", { required: true, secondary: true }),
      col("phone", "Phone", "phone", { secondary: true }),
      col("city", "City", "city"),
      col("branches", "Branches", "number"),
      col("plan", "Plan", "badge", {
        options: ["Starter", "Professional", "Enterprise", "Custom"],
      }),
      col("onboarding", "Onboarding", "badge", { options: ONBOARDING, secondary: true }),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "platform/plans",
    title: "Plans",
    description: "Subscription plans, pricing and usage limits.",
    group: "platform",
    singular: "Plan",
    rowCount: 8,
    columns: [
      col("name", "Plan", "text", { required: true }),
      col("code", "Code", "code", { required: true }),
      col("price", "Monthly Price", "money", { required: true }),
      col("yearly", "Yearly Price", "money"),
      col("branchLimit", "Branch Limit", "number"),
      col("userLimit", "User Limit", "number"),
      col("trialDays", "Trial Days", "number"),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "platform/subscriptions",
    title: "Subscriptions",
    description: "Active, pending and cancelled subscriptions across tenants.",
    group: "platform",
    singular: "Subscription",
    rowCount: 48,
    stats: [
      { label: "MRR", value: "₹ 18,42,000", delta: "+11.4%", trend: "up" },
      { label: "Active subscriptions", value: "371", delta: "+14", trend: "up" },
      { label: "Renewals this month", value: "58" },
      { label: "Churn", value: "1.8%", delta: "-0.3%", trend: "down" },
    ],
    charts: [
      {
        type: "area",
        title: "Recurring revenue",
        dataKeys: ["revenue", "target"],
        categories: ["Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"],
      },
    ],
    columns: [
      col("organization", "Organization", "org", { required: true }),
      col("plan", "Plan", "badge", {
        options: ["Starter", "Professional", "Enterprise", "Custom"],
      }),
      col("amount", "Amount", "money"),
      col("cycle", "Cycle", "badge", { options: ["Monthly", "Yearly"] }),
      col("startDate", "Start", "date"),
      col("renewal", "Renewal", "date"),
      col("status", "Status", "badge", { options: ["Active", "Pending", "Cancelled", "Expired"] }),
    ],
  },
  {
    path: "platform/trials",
    title: "Free Trials",
    description: "Trial accounts, expiry tracking and conversion.",
    group: "platform",
    singular: "Trial",
    rowCount: 26,
    columns: [
      col("organization", "Organization", "org", { required: true }),
      col("plan", "Trial Plan", "badge", { options: ["Starter Trial", "Professional Trial"] }),
      col("startDate", "Started", "date"),
      col("endDate", "Ends", "date"),
      col("daysLeft", "Days Left", "number"),
      col("status", "Status", "badge", { options: ["Active", "Expiring", "Expired", "Converted"] }),
    ],
  },
  {
    path: "platform/demo-requests",
    title: "Demo Requests",
    description: "Product demonstration requests captured from the website.",
    group: "platform",
    singular: "Demo Request",
    rowCount: 34,
    columns: [
      col("name", "Contact", "name", { required: true }),
      col("organization", "Organization", "org", { required: true }),
      col("email", "Email", "email", { required: true }),
      col("phone", "Phone", "phone", { required: true }),
      col("city", "City", "city"),
      col("branches", "Expected Branches", "number"),
      col("scheduled", "Scheduled On", "date"),
      col("status", "Status", "badge", {
        options: ["Requested", "Scheduled", "Completed", "No Show"],
      }),
    ],
  },
  {
    path: "platform/leads",
    title: "Platform Leads",
    description: "Every website form lands in one common lead pipeline.",
    group: "platform",
    singular: "Lead",
    rowCount: 52,
    columns: [
      col("name", "Lead", "name", { required: true }),
      col("organization", "Organization", "org"),
      col("source", "Source", "badge", {
        options: ["Contact Us", "Request Demo", "Free Trial", "Pricing", "Website"],
      }),
      col("email", "Email", "email", { required: true }),
      col("phone", "Phone", "phone"),
      col("owner", "Assigned To", "name", { secondary: true }),
      col("status", "Status", "badge", { options: LEAD_STATUS }),
    ],
  },
  {
    path: "platform/coupons",
    title: "Coupons",
    description: "Promotional discount codes for marketing campaigns.",
    group: "platform",
    singular: "Coupon",
    rowCount: 14,
    columns: [
      col("code", "Code", "code", { required: true }),
      col("discount", "Discount %", "percent", { required: true }),
      col("validFrom", "Valid From", "date"),
      col("validTo", "Valid Until", "date"),
      col("plans", "Applicable Plans", "text", { secondary: true }),
      col("usage", "Redemptions", "number"),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "platform/referrals",
    title: "Referral Codes",
    description: "Future-ready referral programme, disabled for the first release.",
    group: "platform",
    singular: "Referral Code",
    rowCount: 10,
    columns: [
      col("code", "Referral Code", "code", { required: true }),
      col("organization", "Referred By", "org"),
      col("reward", "Reward", "money"),
      col("signups", "Signups", "number"),
      col("status", "Status", "badge", { options: ["Enabled", "Disabled"] }),
    ],
  },
  {
    path: "platform/support",
    title: "Support Tickets",
    description: "Customer support queue with priority and SLA tracking.",
    group: "platform",
    singular: "Ticket",
    rowCount: 30,
    columns: [
      col("code", "Ticket", "code"),
      col("subject", "Subject", "text", { required: true }),
      col("organization", "Organization", "org"),
      col("priority", "Priority", "badge", { options: ["Low", "Medium", "High", "Critical"] }),
      col("owner", "Assigned To", "name", { secondary: true }),
      col("createdAt", "Created", "date"),
      col("status", "Status", "badge", { options: ["Open", "In Progress", "Resolved", "Closed"] }),
    ],
  },
  {
    path: "platform/users",
    title: "Platform Users",
    description: "Internal MediUnivers staff accounts.",
    group: "platform",
    singular: "Platform User",
    rowCount: 18,
    columns: [
      col("name", "Name", "name", { required: true }),
      col("email", "Email", "email", { required: true }),
      col("phone", "Phone", "phone"),
      col("role", "Role", "badge", { options: ["Super Admin", "Sales", "Support", "Finance"] }),
      col("lastLogin", "Last Login", "date", { secondary: true }),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "platform/roles",
    title: "Platform Roles",
    description: "Roles and permission sets for platform staff.",
    group: "platform",
    singular: "Role",
    rowCount: 8,
    columns: [
      col("name", "Role", "text", { required: true }),
      col("code", "Code", "code"),
      col("users", "Users", "number"),
      col("permissions", "Permissions", "number"),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "platform/audit-logs",
    title: "Audit Logs",
    description: "Every privileged action recorded with actor and timestamp.",
    group: "platform",
    singular: "Audit Entry",
    rowCount: 60,
    columns: [
      col("actor", "Actor", "name"),
      col("action", "Action", "badge", {
        options: ["Created", "Updated", "Deleted", "Login", "Export"],
      }),
      col("entity", "Entity", "text"),
      col("organization", "Organization", "org", { secondary: true }),
      col("ip", "IP Address", "code", { secondary: true }),
      col("createdAt", "Timestamp", "date"),
    ],
  },
  {
    path: "platform/cms",
    title: "Website Content",
    description: "Marketing website pages, SEO settings and testimonials.",
    group: "platform",
    singular: "Page",
    rowCount: 16,
    columns: [
      col("title", "Page Title", "text", { required: true }),
      col("slug", "URL Slug", "code", { required: true }),
      col("metaDescription", "Meta Description", "text", {
        secondary: true,
        fieldType: "textarea",
      }),
      col("keywords", "Keywords", "text", { secondary: true }),
      col("visibility", "Search Visibility", "badge", { options: ["Visible", "Hidden"] }),
      col("status", "Status", "badge", { options: ["Published", "Draft"] }),
    ],
  },
  {
    path: "platform/communication",
    title: "Platform Communication",
    description:
      "MediUnivers' own outgoing email/SMS settings, and the wording of every account-security message it sends.",
    group: "platform",
    singular: "Template",
    columns: [],
  },
  {
    path: "platform/testimonials",
    title: "Testimonials",
    description: "Customer quotes shown on MediUnivers' own public website.",
    group: "platform",
    singular: "Testimonial",
    columns: [],
  },
  {
    path: "platform/blog",
    title: "Blog",
    description: "Articles published on MediUnivers' own public website.",
    group: "platform",
    singular: "Blog Post",
    columns: [],
  },
  {
    path: "platform/content-cards",
    title: "Features & Solutions",
    description: "Feature, solution, value and team cards shown on the public website.",
    group: "platform",
    singular: "Content Card",
    columns: [],
  },

  /* ------------------------------- Billing --------------------------------- */
  {
    path: "billing/invoices",
    title: "Invoices",
    description: "Every invoice generated across Clinic, Pharmacy and Laboratory, in one place.",
    group: "billing",
    singular: "Invoice",
    columns: [
      col("invoiceNumber", "Invoice #", "text"),
      col("sourceModule", "Module", "badge", { options: ["CLINIC", "PHARMACY", "LAB", "OTHER"] }),
      col("status", "Status", "badge", {
        options: ["UNPAID", "PARTIALLY_PAID", "PAID", "CANCELLED", "REFUNDED"],
      }),
      col("grandTotal", "Amount", "money"),
    ],
  },

  /* ---------------------------- Organization ------------------------------ */
  {
    path: "org/modules",
    title: "Configure Modules",
    description:
      "Which business modules (Clinic, Pharmacy, Laboratory, CRM, Website) your subscription unlocks.",
    group: "org",
    singular: "Module",
    columns: [
      col("name", "Module", "text"),
      col("status", "Status", "badge", {
        options: ["Enabled", "Needs plan upgrade", "Not part of your business type"],
      }),
    ],
  },
  {
    path: "org/settings",
    title: "Organization Settings",
    description: "Profile, branding, tax details and preferences.",
    group: "org",
    singular: "Setting",
    rowCount: 12,
    columns: [
      col("name", "Setting", "text", { required: true }),
      col("value", "Value", "text", { required: true }),
      col("category", "Category", "badge", {
        options: ["General", "Billing", "Notification", "Security"],
      }),
      col("status", "Status", "badge", { options: ["Enabled", "Disabled"] }),
    ],
  },
  {
    path: "org/branches",
    title: "Branches",
    description: "Branch-level configuration and working hours.",
    group: "org",
    singular: "Branch",
    rowCount: 24,
    columns: [
      col("name", "Branch", "org", { required: true }),
      col("city", "City", "city"),
      col("phone", "Phone", "phone"),
      col("openTime", "Opens", "text", { secondary: true }),
      col("closeTime", "Closes", "text", { secondary: true }),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "org/departments",
    title: "Departments",
    description: "Departments available across your organization.",
    group: "org",
    singular: "Department",
    rowCount: 16,
    columns: [
      col("name", "Department", "text", { required: true }),
      col("code", "Code", "code"),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "org/specializations",
    title: "Specializations",
    description: "Doctor specializations available across your organization.",
    group: "org",
    singular: "Specialization",
    rowCount: 14,
    columns: [
      col("name", "Specialization", "text", { required: true }),
      col("code", "Code", "code"),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "org/tax-rules",
    title: "Tax Rules",
    description: "Named GST/tax slabs your organization can bill against.",
    group: "org",
    singular: "Tax rule",
    rowCount: 8,
    columns: [
      col("name", "Tax rule", "text", { required: true }),
      col("code", "Code", "code"),
      col("percentage", "Rate (%)", "percent"),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "org/users",
    title: "Users",
    description: "Staff accounts with role and branch access.",
    group: "org",
    singular: "User",
    rowCount: 40,
    columns: [
      col("name", "Name", "name", { required: true }),
      col("email", "Email", "email", { required: true }),
      col("phone", "Phone", "phone", { required: true }),
      col("role", "Role", "badge", {
        options: [
          "Org Admin",
          "Clinic Admin",
          "Doctor",
          "Receptionist",
          "Pharmacist",
          "Lab Technician",
        ],
      }),
      col("branch", "Branch", "org", { secondary: true }),
      col("lastLogin", "Last Login", "date", { secondary: true }),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "org/roles",
    title: "Roles & Permissions",
    description: "Dynamic roles that drive menus and route access.",
    group: "org",
    singular: "Role",
    rowCount: 12,
    columns: [
      col("name", "Role", "text", { required: true }),
      col("code", "Code", "code"),
      col("users", "Users", "number"),
      col("permissions", "Permissions", "number"),
      col("scope", "Scope", "badge", { options: ["Organization", "Clinic", "Branch"] }),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "org/plans",
    title: "Subscription & Billing",
    description: "Current plan, usage and upgrade options.",
    group: "org",
    singular: "Plan",
    columns: [],
  },
  {
    path: "org/onboarding",
    title: "Onboarding Checklist",
    description: "Your organization's own go-live checklist.",
    group: "org",
    singular: "Onboarding Step",
    columns: [],
  },
  {
    path: "org/communication",
    title: "Communication Settings",
    description:
      "Turn Email, SMS and WhatsApp on or off and configure your own provider credentials.",
    group: "org",
    singular: "Channel",
    columns: [
      col("name", "Channel", "text", { required: true }),
      col("status", "Status", "badge", { options: ["Enabled", "Disabled"] }),
    ],
  },
  {
    path: "org/notification-templates",
    title: "Notification Templates",
    description:
      "Edit the wording of every notification this organization sends — nothing is hardcoded.",
    group: "org",
    singular: "Template",
    columns: [
      col("name", "Template", "text", { required: true }),
      col("channel", "Channel", "badge", { options: ["EMAIL", "SMS", "WHATSAPP", "IN_APP"] }),
      col("status", "Status", "badge", { options: ["Active", "Inactive"] }),
    ],
  },
  {
    path: "org/notifications",
    title: "Notification Logs",
    description: "Every email, SMS, WhatsApp and in-app send attempt, most recent first.",
    group: "org",
    singular: "Notification",
    columns: [
      col("event", "Event", "text", { required: true }),
      col("channel", "Channel", "badge", { options: ["EMAIL", "SMS", "WHATSAPP", "IN_APP"] }),
      col("status", "Status", "badge", { options: ["PENDING", "SENT", "FAILED", "EXPIRED"] }),
    ],
  },

  /* -------------------------------- Clinic -------------------------------- */
  {
    path: "clinic/patients",
    title: "Patients",
    description: "Patient master with demographics and contact details.",
    group: "clinic",
    singular: "Patient",
    rowCount: 80,
    stats: [
      { label: "Total patients", value: "12,480", delta: "+320", trend: "up" },
      { label: "New this month", value: "486", delta: "+6.4%", trend: "up" },
      { label: "Follow-ups due", value: "94" },
      { label: "Average age", value: "37" },
    ],
    columns: [
      col("code", "UHID", "code"),
      col("name", "Patient", "name", { required: true }),
      col("gender", "Gender", "badge", { options: ["Male", "Female", "Other"] }),
      col("age", "Age", "number"),
      col("phone", "Phone", "phone", { required: true }),
      col("city", "City", "city", { secondary: true }),
      col("lastVisit", "Last Visit", "date", { secondary: true }),
      col("status", "Status", "badge", { options: ["Active", "Inactive"] }),
    ],
  },
  {
    path: "clinic/appointments",
    title: "Appointments",
    description: "Scheduled consultations across doctors and branches.",
    group: "clinic",
    singular: "Appointment",
    rowCount: 60,
    charts: [
      {
        type: "bar",
        title: "Appointments per day",
        dataKeys: ["booked", "completed"],
        categories: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      },
    ],
    columns: [
      col("code", "Ref", "code"),
      col("patient", "Patient", "name", { required: true }),
      col("doctor", "Doctor", "name", { required: true }),
      col("department", "Department", "badge", {
        options: ["General", "Dental", "Cardiology", "Paediatrics", "Dermatology"],
      }),
      col("date", "Date", "date", { required: true }),
      col("slot", "Slot", "text"),
      col("type", "Type", "badge", { options: ["Walk-in", "Online", "Follow-up"] }),
      col("status", "Status", "badge", {
        options: ["Scheduled", "Checked In", "Completed", "Cancelled"],
      }),
    ],
  },
  {
    path: "clinic/walk-in",
    title: "Walk-In Registration",
    description: "Fast registration desk for unscheduled patients.",
    group: "clinic",
    singular: "Walk-In",
    rowCount: 24,
    columns: [
      col("name", "Patient", "name", { required: true }),
      col("phone", "Phone", "phone", { required: true }),
      col("gender", "Gender", "badge", { options: ["Male", "Female", "Other"] }),
      col("age", "Age", "number", { required: true }),
      col("doctor", "Doctor", "name"),
      col("token", "Token", "number"),
      col("status", "Status", "badge", { options: ["Waiting", "In Consultation", "Done"] }),
    ],
  },
  {
    path: "clinic/reception",
    title: "Reception Desk",
    description: "Check-in, payments and visitor handling.",
    group: "clinic",
    singular: "Visit",
    rowCount: 28,
    columns: [
      col("token", "Token", "number"),
      col("patient", "Patient", "name", { required: true }),
      col("doctor", "Doctor", "name"),
      col("checkIn", "Check-In", "text"),
      col("fee", "Consultation Fee", "money"),
      col("payment", "Payment", "badge", { options: ["Paid", "Pending", "Insurance"] }),
      col("status", "Status", "badge", { options: ["Waiting", "In Progress", "Completed"] }),
    ],
  },
  {
    path: "clinic/queue",
    title: "Queue Management",
    description: "Live token queue per doctor and room.",
    group: "clinic",
    singular: "Queue Entry",
    rowCount: 18,
    columns: [
      col("token", "Token", "number"),
      col("patient", "Patient", "name", { required: true }),
      col("doctor", "Doctor", "name"),
      col("room", "Room", "code"),
      col("waitTime", "Wait (min)", "number"),
      col("status", "Status", "badge", {
        options: ["Waiting", "Called", "In Consultation", "Completed"],
      }),
    ],
  },
  {
    path: "clinic/consultations",
    title: "Consultations",
    description: "Clinical notes, vitals, diagnosis and advice.",
    group: "clinic",
    singular: "Consultation",
    rowCount: 44,
    columns: [
      col("code", "Consultation", "code"),
      col("patient", "Patient", "name", { required: true }),
      col("doctor", "Doctor", "name", { required: true }),
      col("date", "Date", "date"),
      col("diagnosis", "Diagnosis", "text", { fieldType: "textarea" }),
      col("followUp", "Follow-Up", "date", { secondary: true }),
      col("status", "Status", "badge", { options: ["Draft", "Completed"] }),
    ],
  },
  {
    path: "clinic/prescriptions",
    title: "Prescriptions",
    description: "Digital prescriptions ready for pharmacy dispensing.",
    group: "clinic",
    singular: "Prescription",
    rowCount: 40,
    columns: [
      col("code", "Rx No", "code"),
      col("patient", "Patient", "name", { required: true }),
      col("doctor", "Doctor", "name"),
      col("date", "Date", "date"),
      col("items", "Medicines", "number"),
      col("status", "Status", "badge", { options: ["Issued", "Partially Dispensed", "Dispensed"] }),
    ],
  },
  {
    path: "clinic/doctors",
    title: "Doctors",
    description: "Doctor profiles, specialisation and consultation fees.",
    group: "clinic",
    singular: "Doctor",
    rowCount: 26,
    columns: [
      col("name", "Doctor", "name", { required: true }),
      col("specialisation", "Specialisation", "badge", {
        options: ["General Physician", "Dentist", "Cardiologist", "Paediatrician", "Dermatologist"],
      }),
      col("email", "Email", "email", { required: true }),
      col("phone", "Phone", "phone", { required: true }),
      col("experience", "Experience (yrs)", "number"),
      col("fee", "Fee", "money"),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "clinic/availability",
    title: "Doctor Availability",
    description: "Weekly slots, leave and consulting rooms.",
    group: "clinic",
    singular: "Availability",
    rowCount: 30,
    columns: [
      col("doctor", "Doctor", "name", { required: true }),
      col("day", "Day", "badge", { options: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"] }),
      col("openTime", "From", "text"),
      col("closeTime", "To", "text"),
      col("slotSize", "Slot (min)", "number"),
      col("room", "Room", "code", { secondary: true }),
      col("status", "Status", "badge", { options: ["Available", "On Leave"] }),
    ],
  },
  {
    path: "clinic/billing",
    title: "Clinic Billing",
    description: "Consultation and procedure invoices.",
    group: "clinic",
    singular: "Bill",
    rowCount: 46,
    stats: [
      { label: "Collected today", value: "₹ 1,24,500", delta: "+9%", trend: "up" },
      { label: "Pending", value: "₹ 42,300", delta: "-4%", trend: "down" },
      { label: "Invoices", value: "168" },
      { label: "Average bill", value: "₹ 740" },
    ],
    columns: [
      col("code", "Invoice", "code"),
      col("patient", "Patient", "name", { required: true }),
      col("doctor", "Doctor", "name", { secondary: true }),
      col("date", "Date", "date"),
      col("amount", "Amount", "money", { required: true }),
      col("discount", "Discount %", "percent", { secondary: true }),
      col("payment", "Mode", "badge", { options: ["Cash", "Card", "UPI", "Online"] }),
      col("status", "Status", "badge", { options: ["Paid", "Pending", "Refunded"] }),
    ],
  },
  {
    path: "clinic/reports",
    title: "Clinic Reports",
    description: "Operational reports across visits, revenue and doctors.",
    group: "clinic",
    singular: "Report",
    rowCount: 14,
    charts: [
      {
        type: "line",
        title: "Visits trend",
        dataKeys: ["visits", "newPatients"],
        categories: ["Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"],
      },
      {
        type: "pie",
        title: "Department mix",
        dataKeys: ["value"],
        categories: ["General", "Dental", "Cardiology", "Paediatrics", "Dermatology"],
      },
    ],
    columns: [
      col("name", "Report", "text", { required: true }),
      col("category", "Category", "badge", {
        options: ["Revenue", "Patients", "Doctors", "Operations"],
      }),
      col("period", "Period", "badge", { options: ["Daily", "Weekly", "Monthly"] }),
      col("generatedAt", "Generated", "date"),
      col("status", "Status", "badge", { options: ["Ready", "Scheduled"] }),
    ],
  },

  /* ------------------------------- Pharmacy ------------------------------- */
  {
    path: "pharmacy/categories",
    title: "Medicine Categories",
    description: "Therapeutic categories for the medicine master.",
    group: "pharmacy",
    singular: "Category",
    rowCount: 16,
    columns: [
      col("name", "Category", "text", { required: true }),
      col("code", "Code", "code"),
      col("medicines", "Medicines", "number"),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "pharmacy/units",
    title: "Medicine Units",
    description: "Dosage/measurement units for the medicine master (tablet, ml, mg...).",
    group: "pharmacy",
    singular: "Unit",
    rowCount: 10,
    columns: [
      col("name", "Unit", "text", { required: true }),
      col("code", "Code", "code"),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "pharmacy/medicines",
    title: "Medicine Master",
    description: "Complete medicine catalogue with pricing and stock.",
    group: "pharmacy",
    singular: "Medicine",
    rowCount: 70,
    stats: [
      { label: "SKUs", value: "1,284" },
      { label: "Low stock", value: "36", delta: "+4", trend: "up" },
      { label: "Expiring in 30d", value: "18" },
      { label: "Stock value", value: "₹ 42,10,000" },
    ],
    columns: [
      col("name", "Medicine", "text", { required: true }),
      col("category", "Category", "badge", {
        options: ["Antibiotic", "Analgesic", "Cardiac", "Vitamin", "Dermal"],
      }),
      col("manufacturer", "Manufacturer", "org", { secondary: true }),
      col("batch", "Batch", "code", { secondary: true }),
      col("mrp", "MRP", "money", { required: true }),
      col("stock", "Stock", "number"),
      col("expiry", "Expiry", "date"),
      col("status", "Status", "badge", { options: ["In Stock", "Low Stock", "Out of Stock"] }),
    ],
  },
  {
    path: "pharmacy/manufacturers",
    title: "Manufacturers",
    description: "Pharmaceutical manufacturers and their catalogues.",
    group: "pharmacy",
    singular: "Manufacturer",
    rowCount: 20,
    columns: [
      col("name", "Manufacturer", "org", { required: true }),
      col("code", "Code", "code"),
      col("city", "City", "city"),
      col("phone", "Phone", "phone"),
      col("medicines", "Medicines", "number"),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "pharmacy/suppliers",
    title: "Suppliers",
    description: "Distributors, credit terms and purchase history.",
    group: "pharmacy",
    singular: "Supplier",
    rowCount: 22,
    columns: [
      col("name", "Supplier", "org", { required: true }),
      col("contact", "Contact Person", "name"),
      col("phone", "Phone", "phone", { required: true }),
      col("city", "City", "city"),
      col("creditDays", "Credit Days", "number"),
      col("outstanding", "Outstanding", "money", { secondary: true }),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "pharmacy/purchases",
    title: "Purchases",
    description: "Purchase orders and goods received notes.",
    group: "pharmacy",
    singular: "Purchase",
    rowCount: 34,
    columns: [
      col("code", "PO No", "code"),
      col("supplier", "Supplier", "org", { required: true }),
      col("date", "Date", "date"),
      col("items", "Items", "number"),
      col("amount", "Amount", "money", { required: true }),
      col("payment", "Payment", "badge", { options: ["Paid", "Partial", "Credit"] }),
      col("status", "Status", "badge", { options: ["Draft", "Ordered", "Received", "Cancelled"] }),
    ],
  },
  {
    path: "pharmacy/batches",
    title: "Batch & Expiry",
    description: "Batch-wise stock with expiry monitoring.",
    group: "pharmacy",
    singular: "Batch",
    rowCount: 48,
    columns: [
      col("batch", "Batch", "code", { required: true }),
      col("medicine", "Medicine", "text", { required: true }),
      col("quantity", "Quantity", "number"),
      col("mrp", "MRP", "money"),
      col("expiry", "Expiry", "date", { required: true }),
      col("daysLeft", "Days To Expiry", "number"),
      col("status", "Status", "badge", { options: ["Good", "Near Expiry", "Expired"] }),
    ],
  },
  {
    path: "pharmacy/stock",
    title: "Stock",
    description: "Live stock levels, reorder points and transfers.",
    group: "pharmacy",
    singular: "Stock Item",
    rowCount: 50,
    columns: [
      col("medicine", "Medicine", "text", { required: true }),
      col("branch", "Branch", "org"),
      col("stock", "On Hand", "number"),
      col("reorder", "Reorder Level", "number"),
      col("value", "Stock Value", "money", { secondary: true }),
      col("status", "Status", "badge", { options: ["In Stock", "Low Stock", "Out of Stock"] }),
    ],
  },
  {
    path: "pharmacy/dispensing",
    title: "Prescription Dispensing",
    description: "Dispense medicines against clinic prescriptions.",
    group: "pharmacy",
    singular: "Dispense",
    rowCount: 32,
    columns: [
      col("code", "Rx No", "code"),
      col("patient", "Patient", "name", { required: true }),
      col("doctor", "Doctor", "name", { secondary: true }),
      col("items", "Items", "number"),
      col("amount", "Amount", "money"),
      col("date", "Date", "date"),
      col("status", "Status", "badge", {
        options: ["Pending", "Partially Dispensed", "Dispensed"],
      }),
    ],
  },
  {
    path: "pharmacy/sales",
    title: "Direct Sales",
    description: "Over-the-counter pharmacy billing.",
    group: "pharmacy",
    singular: "Sale",
    rowCount: 40,
    columns: [
      col("code", "Bill No", "code"),
      col("customer", "Customer", "name", { required: true }),
      col("items", "Items", "number"),
      col("amount", "Amount", "money", { required: true }),
      col("discount", "Discount %", "percent", { secondary: true }),
      col("payment", "Mode", "badge", { options: ["Cash", "Card", "UPI"] }),
      col("date", "Date", "date"),
    ],
  },
  {
    path: "pharmacy/returns",
    title: "Returns",
    description: "Customer and supplier return handling.",
    group: "pharmacy",
    singular: "Return",
    rowCount: 18,
    columns: [
      col("code", "Return No", "code"),
      col("type", "Type", "badge", { options: ["Customer", "Supplier"] }),
      col("reference", "Reference", "code"),
      col("items", "Items", "number"),
      col("amount", "Amount", "money"),
      col("reason", "Reason", "text", { secondary: true, fieldType: "textarea" }),
      col("status", "Status", "badge", { options: ["Requested", "Approved", "Rejected"] }),
    ],
  },
  {
    path: "pharmacy/alerts",
    title: "Stock Alerts",
    description: "Low stock and expiry alerts in one queue.",
    group: "pharmacy",
    singular: "Alert",
    rowCount: 24,
    columns: [
      col("medicine", "Medicine", "text", { required: true }),
      col("type", "Alert Type", "badge", { options: ["Low Stock", "Near Expiry", "Expired"] }),
      col("branch", "Branch", "org"),
      col("stock", "Stock", "number"),
      col("expiry", "Expiry", "date"),
      col("status", "Status", "badge", { options: ["Open", "Acknowledged", "Resolved"] }),
    ],
  },
  {
    path: "pharmacy/reports",
    title: "Pharmacy Reports",
    description: "Sales, purchase, stock and expiry reporting.",
    group: "pharmacy",
    singular: "Report",
    rowCount: 12,
    charts: [
      {
        type: "bar",
        title: "Sales vs purchases",
        dataKeys: ["sales", "purchases"],
        categories: ["Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"],
      },
    ],
    columns: [
      col("name", "Report", "text", { required: true }),
      col("category", "Category", "badge", { options: ["Sales", "Purchase", "Stock", "Expiry"] }),
      col("period", "Period", "badge", { options: ["Daily", "Weekly", "Monthly"] }),
      col("generatedAt", "Generated", "date"),
      col("status", "Status", "badge", { options: ["Ready", "Scheduled"] }),
    ],
  },

  /* ------------------------------ Laboratory ------------------------------ */
  {
    path: "lab/categories",
    title: "Test Categories",
    description: "Grouping for laboratory investigations.",
    group: "lab",
    singular: "Test Category",
    rowCount: 14,
    columns: [
      col("name", "Category", "text", { required: true }),
      col("code", "Code", "code"),
      col("tests", "Tests", "number"),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "lab/tests",
    title: "Tests",
    description: "Test master with sample type, method and pricing.",
    group: "lab",
    singular: "Test",
    rowCount: 46,
    columns: [
      col("name", "Test", "text", { required: true }),
      col("category", "Category", "badge", {
        options: ["Haematology", "Biochemistry", "Microbiology", "Radiology"],
      }),
      col("code", "Code", "code"),
      col("sample", "Sample", "badge", { options: ["Blood", "Urine", "Swab", "Tissue"] }),
      col("tat", "TAT (hrs)", "number"),
      col("price", "Price", "money", { required: true }),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "lab/packages",
    title: "Test Packages",
    description: "Bundled health checkup packages.",
    group: "lab",
    singular: "Package",
    rowCount: 12,
    columns: [
      col("name", "Package", "text", { required: true }),
      col("tests", "Tests", "number"),
      col("price", "Price", "money", { required: true }),
      col("discount", "Discount %", "percent"),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "lab/orders",
    title: "Lab Orders",
    description: "Test orders raised from clinics and walk-ins.",
    group: "lab",
    singular: "Order",
    rowCount: 44,
    stats: [
      { label: "Orders today", value: "142", delta: "+12", trend: "up" },
      { label: "Pending results", value: "37" },
      { label: "Average TAT", value: "6.4 hrs", delta: "-0.6", trend: "down" },
      { label: "Revenue today", value: "₹ 86,400" },
    ],
    columns: [
      col("code", "Order No", "code"),
      col("patient", "Patient", "name", { required: true }),
      col("doctor", "Referred By", "name", { secondary: true }),
      col("tests", "Tests", "number"),
      col("amount", "Amount", "money"),
      col("date", "Date", "date"),
      col("status", "Status", "badge", {
        options: ["Ordered", "Sample Collected", "Processing", "Reported"],
      }),
    ],
  },
  {
    path: "lab/samples",
    title: "Sample Tracking",
    description: "Collection, barcode and chain of custody.",
    group: "lab",
    singular: "Sample",
    rowCount: 40,
    columns: [
      col("code", "Barcode", "code", { required: true }),
      col("patient", "Patient", "name"),
      col("sample", "Sample Type", "badge", { options: ["Blood", "Urine", "Swab", "Tissue"] }),
      col("collectedBy", "Collected By", "name", { secondary: true }),
      col("collectedAt", "Collected At", "date"),
      col("status", "Status", "badge", {
        options: ["Pending", "Collected", "In Transit", "Received", "Rejected"],
      }),
    ],
  },
  {
    path: "lab/processing",
    title: "Test Processing",
    description: "Work bench for technicians with instrument mapping.",
    group: "lab",
    singular: "Processing Job",
    rowCount: 30,
    columns: [
      col("code", "Order No", "code"),
      col("test", "Test", "text", { required: true }),
      col("technician", "Technician", "name"),
      col("instrument", "Instrument", "code", { secondary: true }),
      col("startedAt", "Started", "date"),
      col("status", "Status", "badge", { options: ["Queued", "Running", "Completed", "Repeat"] }),
    ],
  },
  {
    path: "lab/results",
    title: "Results",
    description: "Result entry with reference ranges and flags.",
    group: "lab",
    singular: "Result",
    rowCount: 42,
    columns: [
      col("code", "Order No", "code"),
      col("patient", "Patient", "name", { required: true }),
      col("test", "Test", "text", { required: true }),
      col("value", "Value", "text"),
      col("range", "Reference Range", "text", { secondary: true }),
      col("flag", "Flag", "badge", { options: ["Normal", "High", "Low", "Critical"] }),
      col("status", "Status", "badge", { options: ["Draft", "Verified", "Released"] }),
    ],
  },
  {
    path: "lab/review",
    title: "Doctor Review",
    description: "Pathologist verification before release.",
    group: "lab",
    singular: "Review",
    rowCount: 26,
    columns: [
      col("code", "Report No", "code"),
      col("patient", "Patient", "name", { required: true }),
      col("reviewer", "Reviewer", "name"),
      col("submittedAt", "Submitted", "date"),
      col("remarks", "Remarks", "text", { secondary: true, fieldType: "textarea" }),
      col("status", "Status", "badge", { options: ["Pending", "Approved", "Rework"] }),
    ],
  },
  {
    path: "lab/reports",
    title: "Lab Reports",
    description: "Released reports available to doctors and patients.",
    group: "lab",
    singular: "Report",
    rowCount: 38,
    columns: [
      col("code", "Report No", "code"),
      col("patient", "Patient", "name", { required: true }),
      col("tests", "Tests", "number"),
      col("releasedAt", "Released", "date"),
      col("delivery", "Delivery", "badge", { options: ["Portal", "Email", "WhatsApp", "Printed"] }),
      col("status", "Status", "badge", { options: ["Released", "Amended"] }),
    ],
  },

  /* --------------------------------- CRM ---------------------------------- */
  {
    path: "crm/sources",
    title: "Lead Sources",
    description: "Channels that generate enquiries.",
    group: "crm",
    singular: "Lead Source",
    rowCount: 10,
    columns: [
      col("name", "Source", "text", { required: true }),
      col("code", "Code", "code"),
      col("leads", "Leads", "number"),
      col("conversion", "Conversion %", "percent"),
      col("status", "Status", "badge", { options: STATUS }),
    ],
  },
  {
    path: "crm/leads",
    title: "Leads",
    description: "Pipeline view of every enquiry with owner and stage.",
    group: "crm",
    singular: "Lead",
    rowCount: 56,
    kanban: true,
    stats: [
      { label: "Open leads", value: "218", delta: "+18", trend: "up" },
      { label: "Demos scheduled", value: "42" },
      { label: "Won this month", value: "27", delta: "+5", trend: "up" },
      { label: "Conversion", value: "18.4%", delta: "+1.2%", trend: "up" },
    ],
    columns: [
      col("name", "Lead", "name", { required: true }),
      col("organization", "Organization", "org"),
      col("source", "Source", "badge", {
        options: ["Website", "Referral", "Campaign", "Walk-in", "Call"],
      }),
      col("phone", "Phone", "phone", { required: true }),
      col("email", "Email", "email"),
      col("owner", "Owner", "name", { secondary: true }),
      col("value", "Deal Value", "money", { secondary: true }),
      col("status", "Stage", "badge", { options: LEAD_STATUS }),
    ],
  },
  {
    path: "crm/follow-ups",
    title: "Follow-Ups",
    description: "Scheduled calls, visits and reminders.",
    group: "crm",
    singular: "Follow-Up",
    rowCount: 34,
    columns: [
      col("lead", "Lead", "name", { required: true }),
      col("type", "Type", "badge", { options: ["Call", "Email", "Visit", "WhatsApp"] }),
      col("owner", "Owner", "name"),
      col("dueDate", "Due", "date", { required: true }),
      col("notes", "Notes", "text", { secondary: true, fieldType: "textarea" }),
      col("status", "Status", "badge", { options: ["Pending", "Done", "Missed"] }),
    ],
  },
  {
    path: "crm/activities",
    title: "Activities",
    description: "Timeline of every interaction logged by the team.",
    group: "crm",
    singular: "Activity",
    rowCount: 44,
    columns: [
      col("lead", "Lead", "name"),
      col("activity", "Activity", "badge", {
        options: ["Call", "Email", "Meeting", "Note", "Status Change"],
      }),
      col("owner", "By", "name"),
      col("createdAt", "When", "date"),
      col("notes", "Summary", "text", { secondary: true, fieldType: "textarea" }),
    ],
  },
  {
    path: "crm/reports",
    title: "CRM Reports",
    description: "Pipeline, source and owner performance.",
    group: "crm",
    singular: "Report",
    rowCount: 10,
    charts: [
      {
        type: "pie",
        title: "Leads by source",
        dataKeys: ["value"],
        categories: ["Website", "Referral", "Campaign", "Walk-in", "Call"],
      },
      {
        type: "area",
        title: "Pipeline value",
        dataKeys: ["pipeline", "won"],
        categories: ["Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"],
      },
    ],
    columns: [
      col("name", "Report", "text", { required: true }),
      col("category", "Category", "badge", {
        options: ["Pipeline", "Source", "Owner", "Conversion"],
      }),
      col("period", "Period", "badge", { options: ["Weekly", "Monthly", "Quarterly"] }),
      col("generatedAt", "Generated", "date"),
      col("status", "Status", "badge", { options: ["Ready", "Scheduled"] }),
    ],
  },

  /* --------------------------- Website / CMS ------------------------------ */
  {
    path: "cms/templates",
    title: "Website Templates",
    description: "Curated templates you can apply to your public site from Branding.",
    group: "cms",
    singular: "Template",
    columns: [],
  },
  {
    path: "cms/branding",
    title: "Branding",
    description: "Logo, colours and typography for the public site.",
    group: "cms",
    singular: "Brand Setting",
    rowCount: 8,
    columns: [
      col("name", "Setting", "text", { required: true }),
      col("value", "Value", "text", { required: true }),
      col("category", "Group", "badge", { options: ["Logo", "Colour", "Typography", "Favicon"] }),
      col("status", "Status", "badge", { options: ["Applied", "Draft"] }),
    ],
  },
  {
    path: "cms/services",
    title: "Services",
    description: "Services listed on the customer website.",
    group: "cms",
    singular: "Service",
    rowCount: 16,
    columns: [
      col("name", "Service", "text", { required: true }),
      col("category", "Category", "badge", {
        options: ["Consultation", "Diagnostics", "Dental", "Wellness"],
      }),
      col("price", "From Price", "money"),
      col("order", "Display Order", "number"),
      col("status", "Status", "badge", { options: ["Visible", "Hidden"] }),
    ],
  },
  {
    path: "cms/gallery",
    title: "Gallery",
    description: "Photos of the facility, team and events.",
    group: "cms",
    singular: "Gallery Item",
    rowCount: 18,
    columns: [
      col("title", "Title", "text", { required: true }),
      col("category", "Album", "badge", { options: ["Facility", "Team", "Events", "Awards"] }),
      col("order", "Order", "number"),
      col("updatedAt", "Updated", "date"),
      col("status", "Status", "badge", { options: ["Visible", "Hidden"] }),
    ],
  },
  {
    path: "cms/testimonials",
    title: "Testimonials",
    description: "Customer reviews shown on the marketing site.",
    group: "cms",
    singular: "Testimonial",
    rowCount: 16,
    columns: [
      col("name", "Customer", "name", { required: true }),
      col("organization", "Clinic", "org"),
      col("designation", "Designation", "text", { secondary: true }),
      col("rating", "Rating", "number"),
      col("review", "Review", "text", { secondary: true, fieldType: "textarea" }),
      col("status", "Display", "badge", { options: ["Enabled", "Disabled"] }),
    ],
  },
  {
    path: "cms/blogs",
    title: "Blogs",
    description: "Articles and health tips published on the website.",
    group: "cms",
    singular: "Blog Post",
    rowCount: 20,
    columns: [
      col("title", "Title", "text", { required: true }),
      col("slug", "Slug", "code"),
      col("author", "Author", "name"),
      col("category", "Category", "badge", { options: ["Health", "Product", "News", "Guides"] }),
      col("publishedAt", "Published", "date"),
      col("status", "Status", "badge", { options: ["Published", "Draft", "Scheduled"] }),
    ],
  },
  {
    path: "cms/enquiries",
    title: "Website Enquiries",
    description: "Contact form and appointment enquiries from the site.",
    group: "cms",
    singular: "Enquiry",
    rowCount: 30,
    columns: [
      col("name", "Name", "name", { required: true }),
      col("email", "Email", "email", { required: true }),
      col("phone", "Phone", "phone", { required: true }),
      col("subject", "Subject", "text"),
      col("createdAt", "Received", "date"),
      col("status", "Status", "badge", { options: ["New", "Responded", "Closed"] }),
    ],
  },

  /* ------------------------------- Patient -------------------------------- */
  {
    path: "patient/book",
    title: "Book a Slot",
    description: "Pick a clinic, doctor, date and available time slot.",
    group: "patient",
    singular: "Booking",
    rowCount: 6,
    columns: [
      col("doctor", "Doctor", "name"),
      col("date", "Date", "date"),
      col("slot", "Slot", "text"),
      col("status", "Status", "badge", { options: ["Scheduled"] }),
    ],
  },
  {
    path: "patient/appointments",
    title: "My Appointments",
    description: "Upcoming and past consultations.",
    group: "patient",
    singular: "Appointment",
    rowCount: 12,
    columns: [
      col("code", "Ref", "code"),
      col("doctor", "Doctor", "name"),
      col("department", "Department", "badge", { options: ["General", "Dental", "Cardiology"] }),
      col("date", "Date", "date"),
      col("slot", "Slot", "text"),
      col("status", "Status", "badge", { options: ["Scheduled", "Completed", "Cancelled"] }),
    ],
  },
  {
    path: "patient/prescriptions",
    title: "My Prescriptions",
    description: "Digital prescriptions issued by your doctors.",
    group: "patient",
    singular: "Prescription",
    rowCount: 10,
    columns: [
      col("code", "Rx No", "code"),
      col("doctor", "Doctor", "name"),
      col("date", "Date", "date"),
      col("items", "Medicines", "number"),
      col("status", "Status", "badge", { options: ["Issued", "Dispensed"] }),
    ],
  },
  {
    path: "patient/reports",
    title: "My Lab Reports",
    description: "Released laboratory reports.",
    group: "patient",
    singular: "Report",
    rowCount: 10,
    columns: [
      col("code", "Report No", "code"),
      col("test", "Test", "text"),
      col("releasedAt", "Released", "date"),
      col("flag", "Flag", "badge", { options: ["Normal", "High", "Low"] }),
      col("status", "Status", "badge", { options: ["Released"] }),
    ],
  },
  {
    path: "patient/invoices",
    title: "My Invoices",
    description: "Payment history and receipts.",
    group: "patient",
    singular: "Invoice",
    rowCount: 12,
    columns: [
      col("code", "Invoice", "code"),
      col("date", "Date", "date"),
      col("amount", "Amount", "money"),
      col("payment", "Mode", "badge", { options: ["Cash", "Card", "UPI"] }),
      col("status", "Status", "badge", { options: ["Paid", "Pending"] }),
    ],
  },
  {
    path: "patient/family",
    title: "My Family",
    description: "Family members registered under your patient record.",
    group: "patient",
    singular: "Family Member",
    rowCount: 4,
    columns: [
      col("name", "Name", "text"),
      col("relation", "Relation", "text"),
      col("gender", "Gender", "badge", { options: ["Male", "Female"] }),
      col("dob", "Date of Birth", "date"),
    ],
  },
];

export const moduleByPath = (path: string) => MODULES.find((m) => m.path === path);
