/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteImport } from './routes/app'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FreeTrialRouteImport } from './routes/free-trial'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RequestDemoRouteImport } from './routes/request-demo'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSplatRouteImport } from './routes/app.$'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'
import { Route as AppBillingInvoicesRouteImport } from './routes/app.billing.invoices'
import { Route as AppClinicAppointmentsRouteImport } from './routes/app.clinic.appointments'
import { Route as AppClinicConsultationsRouteImport } from './routes/app.clinic.consultations'
import { Route as AppClinicDoctorsRouteImport } from './routes/app.clinic.doctors'
import { Route as AppClinicPatientsRouteImport } from './routes/app.clinic.patients'
import { Route as AppCmsBlogsRouteImport } from './routes/app.cms.blogs'
import { Route as AppCmsBrandingRouteImport } from './routes/app.cms.branding'
import { Route as AppCmsEnquiriesRouteImport } from './routes/app.cms.enquiries'
import { Route as AppCmsGalleryRouteImport } from './routes/app.cms.gallery'
import { Route as AppCmsServicesRouteImport } from './routes/app.cms.services'
import { Route as AppCmsTestimonialsRouteImport } from './routes/app.cms.testimonials'
import { Route as AppLabOrdersRouteImport } from './routes/app.lab.orders'
import { Route as AppLabReportsRouteImport } from './routes/app.lab.reports'
import { Route as AppLabResultsRouteImport } from './routes/app.lab.results'
import { Route as AppLabTestsRouteImport } from './routes/app.lab.tests'
import { Route as AppOrgBranchesRouteImport } from './routes/app.org.branches'
import { Route as AppOrgModulesRouteImport } from './routes/app.org.modules'
import { Route as AppOrgRolesRouteImport } from './routes/app.org.roles'
import { Route as AppOrgSettingsRouteImport } from './routes/app.org.settings'
import { Route as AppOrgUsersRouteImport } from './routes/app.org.users'
import { Route as AppPatientBookRouteImport } from './routes/app.patient.book'
import { Route as AppPharmacyDispensingRouteImport } from './routes/app.pharmacy.dispensing'
import { Route as AppPharmacyMedicinesRouteImport } from './routes/app.pharmacy.medicines'
import { Route as AppPharmacyPurchasesRouteImport } from './routes/app.pharmacy.purchases'
import { Route as AppPharmacyReturnsRouteImport } from './routes/app.pharmacy.returns'
import { Route as AppPharmacySalesRouteImport } from './routes/app.pharmacy.sales'
import { Route as AppPharmacyStockRouteImport } from './routes/app.pharmacy.stock'
import { Route as AppPharmacySuppliersRouteImport } from './routes/app.pharmacy.suppliers'
import { Route as SiteSlugBlogBlogSlugRouteImport } from './routes/site.$slug.blog.$blogSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeTrialRoute = FreeTrialRouteImport.update({
  id: '/free-trial',
  path: '/free-trial',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestDemoRoute = RequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillingInvoicesRoute = AppBillingInvoicesRouteImport.update({
  id: '/billing/invoices',
  path: '/billing/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicAppointmentsRoute = AppClinicAppointmentsRouteImport.update({
  id: '/clinic/appointments',
  path: '/clinic/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicConsultationsRoute = AppClinicConsultationsRouteImport.update({
  id: '/clinic/consultations',
  path: '/clinic/consultations',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicDoctorsRoute = AppClinicDoctorsRouteImport.update({
  id: '/clinic/doctors',
  path: '/clinic/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicPatientsRoute = AppClinicPatientsRouteImport.update({
  id: '/clinic/patients',
  path: '/clinic/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppCmsBlogsRoute = AppCmsBlogsRouteImport.update({
  id: '/cms/blogs',
  path: '/cms/blogs',
  getParentRoute: () => AppRoute,
} as any)
const AppCmsBrandingRoute = AppCmsBrandingRouteImport.update({
  id: '/cms/branding',
  path: '/cms/branding',
  getParentRoute: () => AppRoute,
} as any)
const AppCmsEnquiriesRoute = AppCmsEnquiriesRouteImport.update({
  id: '/cms/enquiries',
  path: '/cms/enquiries',
  getParentRoute: () => AppRoute,
} as any)
const AppCmsGalleryRoute = AppCmsGalleryRouteImport.update({
  id: '/cms/gallery',
  path: '/cms/gallery',
  getParentRoute: () => AppRoute,
} as any)
const AppCmsServicesRoute = AppCmsServicesRouteImport.update({
  id: '/cms/services',
  path: '/cms/services',
  getParentRoute: () => AppRoute,
} as any)
const AppCmsTestimonialsRoute = AppCmsTestimonialsRouteImport.update({
  id: '/cms/testimonials',
  path: '/cms/testimonials',
  getParentRoute: () => AppRoute,
} as any)
const AppLabOrdersRoute = AppLabOrdersRouteImport.update({
  id: '/lab/orders',
  path: '/lab/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppLabReportsRoute = AppLabReportsRouteImport.update({
  id: '/lab/reports',
  path: '/lab/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppLabResultsRoute = AppLabResultsRouteImport.update({
  id: '/lab/results',
  path: '/lab/results',
  getParentRoute: () => AppRoute,
} as any)
const AppLabTestsRoute = AppLabTestsRouteImport.update({
  id: '/lab/tests',
  path: '/lab/tests',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgBranchesRoute = AppOrgBranchesRouteImport.update({
  id: '/org/branches',
  path: '/org/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgModulesRoute = AppOrgModulesRouteImport.update({
  id: '/org/modules',
  path: '/org/modules',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgRolesRoute = AppOrgRolesRouteImport.update({
  id: '/org/roles',
  path: '/org/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgSettingsRoute = AppOrgSettingsRouteImport.update({
  id: '/org/settings',
  path: '/org/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgUsersRoute = AppOrgUsersRouteImport.update({
  id: '/org/users',
  path: '/org/users',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientBookRoute = AppPatientBookRouteImport.update({
  id: '/patient/book',
  path: '/patient/book',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyDispensingRoute = AppPharmacyDispensingRouteImport.update({
  id: '/pharmacy/dispensing',
  path: '/pharmacy/dispensing',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyMedicinesRoute = AppPharmacyMedicinesRouteImport.update({
  id: '/pharmacy/medicines',
  path: '/pharmacy/medicines',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyPurchasesRoute = AppPharmacyPurchasesRouteImport.update({
  id: '/pharmacy/purchases',
  path: '/pharmacy/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyReturnsRoute = AppPharmacyReturnsRouteImport.update({
  id: '/pharmacy/returns',
  path: '/pharmacy/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacySalesRoute = AppPharmacySalesRouteImport.update({
  id: '/pharmacy/sales',
  path: '/pharmacy/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyStockRoute = AppPharmacyStockRouteImport.update({
  id: '/pharmacy/stock',
  path: '/pharmacy/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacySuppliersRoute = AppPharmacySuppliersRouteImport.update({
  id: '/pharmacy/suppliers',
  path: '/pharmacy/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const SiteSlugBlogBlogSlugRoute = SiteSlugBlogBlogSlugRouteImport.update({
  id: '/blog/$blogSlug',
  path: '/blog/$blogSlug',
  getParentRoute: () => SiteSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/free-trial': typeof FreeTrialRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/request-demo': typeof RequestDemoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solutions': typeof SolutionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/app/$': typeof AppSplatRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/site/$slug': typeof SiteSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/billing/invoices': typeof AppBillingInvoicesRoute
  '/app/clinic/appointments': typeof AppClinicAppointmentsRoute
  '/app/clinic/consultations': typeof AppClinicConsultationsRoute
  '/app/clinic/doctors': typeof AppClinicDoctorsRoute
  '/app/clinic/patients': typeof AppClinicPatientsRoute
  '/app/cms/blogs': typeof AppCmsBlogsRoute
  '/app/cms/branding': typeof AppCmsBrandingRoute
  '/app/cms/enquiries': typeof AppCmsEnquiriesRoute
  '/app/cms/gallery': typeof AppCmsGalleryRoute
  '/app/cms/services': typeof AppCmsServicesRoute
  '/app/cms/testimonials': typeof AppCmsTestimonialsRoute
  '/app/lab/orders': typeof AppLabOrdersRoute
  '/app/lab/reports': typeof AppLabReportsRoute
  '/app/lab/results': typeof AppLabResultsRoute
  '/app/lab/tests': typeof AppLabTestsRoute
  '/app/org/branches': typeof AppOrgBranchesRoute
  '/app/org/modules': typeof AppOrgModulesRoute
  '/app/org/roles': typeof AppOrgRolesRoute
  '/app/org/settings': typeof AppOrgSettingsRoute
  '/app/org/users': typeof AppOrgUsersRoute
  '/app/patient/book': typeof AppPatientBookRoute
  '/app/pharmacy/dispensing': typeof AppPharmacyDispensingRoute
  '/app/pharmacy/medicines': typeof AppPharmacyMedicinesRoute
  '/app/pharmacy/purchases': typeof AppPharmacyPurchasesRoute
  '/app/pharmacy/returns': typeof AppPharmacyReturnsRoute
  '/app/pharmacy/sales': typeof AppPharmacySalesRoute
  '/app/pharmacy/stock': typeof AppPharmacyStockRoute
  '/app/pharmacy/suppliers': typeof AppPharmacySuppliersRoute
  '/site/$slug/blog/$blogSlug': typeof SiteSlugBlogBlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/free-trial': typeof FreeTrialRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/request-demo': typeof RequestDemoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solutions': typeof SolutionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/app/$': typeof AppSplatRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/site/$slug': typeof SiteSlugRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/billing/invoices': typeof AppBillingInvoicesRoute
  '/app/clinic/appointments': typeof AppClinicAppointmentsRoute
  '/app/clinic/consultations': typeof AppClinicConsultationsRoute
  '/app/clinic/doctors': typeof AppClinicDoctorsRoute
  '/app/clinic/patients': typeof AppClinicPatientsRoute
  '/app/cms/blogs': typeof AppCmsBlogsRoute
  '/app/cms/branding': typeof AppCmsBrandingRoute
  '/app/cms/enquiries': typeof AppCmsEnquiriesRoute
  '/app/cms/gallery': typeof AppCmsGalleryRoute
  '/app/cms/services': typeof AppCmsServicesRoute
  '/app/cms/testimonials': typeof AppCmsTestimonialsRoute
  '/app/lab/orders': typeof AppLabOrdersRoute
  '/app/lab/reports': typeof AppLabReportsRoute
  '/app/lab/results': typeof AppLabResultsRoute
  '/app/lab/tests': typeof AppLabTestsRoute
  '/app/org/branches': typeof AppOrgBranchesRoute
  '/app/org/modules': typeof AppOrgModulesRoute
  '/app/org/roles': typeof AppOrgRolesRoute
  '/app/org/settings': typeof AppOrgSettingsRoute
  '/app/org/users': typeof AppOrgUsersRoute
  '/app/patient/book': typeof AppPatientBookRoute
  '/app/pharmacy/dispensing': typeof AppPharmacyDispensingRoute
  '/app/pharmacy/medicines': typeof AppPharmacyMedicinesRoute
  '/app/pharmacy/purchases': typeof AppPharmacyPurchasesRoute
  '/app/pharmacy/returns': typeof AppPharmacyReturnsRoute
  '/app/pharmacy/sales': typeof AppPharmacySalesRoute
  '/app/pharmacy/stock': typeof AppPharmacyStockRoute
  '/app/pharmacy/suppliers': typeof AppPharmacySuppliersRoute
  '/site/$slug/blog/$blogSlug': typeof SiteSlugBlogBlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/free-trial': typeof FreeTrialRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/request-demo': typeof RequestDemoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solutions': typeof SolutionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/app/$': typeof AppSplatRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/site/$slug': typeof SiteSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/billing/invoices': typeof AppBillingInvoicesRoute
  '/app/clinic/appointments': typeof AppClinicAppointmentsRoute
  '/app/clinic/consultations': typeof AppClinicConsultationsRoute
  '/app/clinic/doctors': typeof AppClinicDoctorsRoute
  '/app/clinic/patients': typeof AppClinicPatientsRoute
  '/app/cms/blogs': typeof AppCmsBlogsRoute
  '/app/cms/branding': typeof AppCmsBrandingRoute
  '/app/cms/enquiries': typeof AppCmsEnquiriesRoute
  '/app/cms/gallery': typeof AppCmsGalleryRoute
  '/app/cms/services': typeof AppCmsServicesRoute
  '/app/cms/testimonials': typeof AppCmsTestimonialsRoute
  '/app/lab/orders': typeof AppLabOrdersRoute
  '/app/lab/reports': typeof AppLabReportsRoute
  '/app/lab/results': typeof AppLabResultsRoute
  '/app/lab/tests': typeof AppLabTestsRoute
  '/app/org/branches': typeof AppOrgBranchesRoute
  '/app/org/modules': typeof AppOrgModulesRoute
  '/app/org/roles': typeof AppOrgRolesRoute
  '/app/org/settings': typeof AppOrgSettingsRoute
  '/app/org/users': typeof AppOrgUsersRoute
  '/app/patient/book': typeof AppPatientBookRoute
  '/app/pharmacy/dispensing': typeof AppPharmacyDispensingRoute
  '/app/pharmacy/medicines': typeof AppPharmacyMedicinesRoute
  '/app/pharmacy/purchases': typeof AppPharmacyPurchasesRoute
  '/app/pharmacy/returns': typeof AppPharmacyReturnsRoute
  '/app/pharmacy/sales': typeof AppPharmacySalesRoute
  '/app/pharmacy/stock': typeof AppPharmacyStockRoute
  '/app/pharmacy/suppliers': typeof AppPharmacySuppliersRoute
  '/site/$slug/blog/$blogSlug': typeof SiteSlugBlogBlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accept-invite'
    | '/app'
    | '/blog'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/free-trial'
    | '/login'
    | '/pricing'
    | '/request-demo'
    | '/reset-password'
    | '/solutions'
    | '/testimonials'
    | '/app/$'
    | '/oauth/callback'
    | '/site/$slug'
    | '/app/'
    | '/app/billing/invoices'
    | '/app/clinic/appointments'
    | '/app/clinic/consultations'
    | '/app/clinic/doctors'
    | '/app/clinic/patients'
    | '/app/cms/blogs'
    | '/app/cms/branding'
    | '/app/cms/enquiries'
    | '/app/cms/gallery'
    | '/app/cms/services'
    | '/app/cms/testimonials'
    | '/app/lab/orders'
    | '/app/lab/reports'
    | '/app/lab/results'
    | '/app/lab/tests'
    | '/app/org/branches'
    | '/app/org/modules'
    | '/app/org/roles'
    | '/app/org/settings'
    | '/app/org/users'
    | '/app/patient/book'
    | '/app/pharmacy/dispensing'
    | '/app/pharmacy/medicines'
    | '/app/pharmacy/purchases'
    | '/app/pharmacy/returns'
    | '/app/pharmacy/sales'
    | '/app/pharmacy/stock'
    | '/app/pharmacy/suppliers'
    | '/site/$slug/blog/$blogSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accept-invite'
    | '/blog'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/free-trial'
    | '/login'
    | '/pricing'
    | '/request-demo'
    | '/reset-password'
    | '/solutions'
    | '/testimonials'
    | '/app/$'
    | '/oauth/callback'
    | '/site/$slug'
    | '/app'
    | '/app/billing/invoices'
    | '/app/clinic/appointments'
    | '/app/clinic/consultations'
    | '/app/clinic/doctors'
    | '/app/clinic/patients'
    | '/app/cms/blogs'
    | '/app/cms/branding'
    | '/app/cms/enquiries'
    | '/app/cms/gallery'
    | '/app/cms/services'
    | '/app/cms/testimonials'
    | '/app/lab/orders'
    | '/app/lab/reports'
    | '/app/lab/results'
    | '/app/lab/tests'
    | '/app/org/branches'
    | '/app/org/modules'
    | '/app/org/roles'
    | '/app/org/settings'
    | '/app/org/users'
    | '/app/patient/book'
    | '/app/pharmacy/dispensing'
    | '/app/pharmacy/medicines'
    | '/app/pharmacy/purchases'
    | '/app/pharmacy/returns'
    | '/app/pharmacy/sales'
    | '/app/pharmacy/stock'
    | '/app/pharmacy/suppliers'
    | '/site/$slug/blog/$blogSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accept-invite'
    | '/app'
    | '/blog'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/free-trial'
    | '/login'
    | '/pricing'
    | '/request-demo'
    | '/reset-password'
    | '/solutions'
    | '/testimonials'
    | '/app/$'
    | '/oauth/callback'
    | '/site/$slug'
    | '/app/'
    | '/app/billing/invoices'
    | '/app/clinic/appointments'
    | '/app/clinic/consultations'
    | '/app/clinic/doctors'
    | '/app/clinic/patients'
    | '/app/cms/blogs'
    | '/app/cms/branding'
    | '/app/cms/enquiries'
    | '/app/cms/gallery'
    | '/app/cms/services'
    | '/app/cms/testimonials'
    | '/app/lab/orders'
    | '/app/lab/reports'
    | '/app/lab/results'
    | '/app/lab/tests'
    | '/app/org/branches'
    | '/app/org/modules'
    | '/app/org/roles'
    | '/app/org/settings'
    | '/app/org/users'
    | '/app/patient/book'
    | '/app/pharmacy/dispensing'
    | '/app/pharmacy/medicines'
    | '/app/pharmacy/purchases'
    | '/app/pharmacy/returns'
    | '/app/pharmacy/sales'
    | '/app/pharmacy/stock'
    | '/app/pharmacy/suppliers'
    | '/site/$slug/blog/$blogSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AppRoute: typeof AppRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FreeTrialRoute: typeof FreeTrialRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RequestDemoRoute: typeof RequestDemoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SolutionsRoute: typeof SolutionsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  SiteSlugRoute: typeof SiteSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-trial': {
      id: '/free-trial'
      path: '/free-trial'
      fullPath: '/free-trial'
      preLoaderRoute: typeof FreeTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-demo': {
      id: '/request-demo'
      path: '/request-demo'
      fullPath: '/request-demo'
      preLoaderRoute: typeof RequestDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$': {
      id: '/app/$'
      path: '/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/billing/invoices': {
      id: '/app/billing/invoices'
      path: '/billing/invoices'
      fullPath: '/app/billing/invoices'
      preLoaderRoute: typeof AppBillingInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clinic/appointments': {
      id: '/app/clinic/appointments'
      path: '/clinic/appointments'
      fullPath: '/app/clinic/appointments'
      preLoaderRoute: typeof AppClinicAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clinic/consultations': {
      id: '/app/clinic/consultations'
      path: '/clinic/consultations'
      fullPath: '/app/clinic/consultations'
      preLoaderRoute: typeof AppClinicConsultationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clinic/doctors': {
      id: '/app/clinic/doctors'
      path: '/clinic/doctors'
      fullPath: '/app/clinic/doctors'
      preLoaderRoute: typeof AppClinicDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clinic/patients': {
      id: '/app/clinic/patients'
      path: '/clinic/patients'
      fullPath: '/app/clinic/patients'
      preLoaderRoute: typeof AppClinicPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cms/blogs': {
      id: '/app/cms/blogs'
      path: '/cms/blogs'
      fullPath: '/app/cms/blogs'
      preLoaderRoute: typeof AppCmsBlogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cms/branding': {
      id: '/app/cms/branding'
      path: '/cms/branding'
      fullPath: '/app/cms/branding'
      preLoaderRoute: typeof AppCmsBrandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cms/enquiries': {
      id: '/app/cms/enquiries'
      path: '/cms/enquiries'
      fullPath: '/app/cms/enquiries'
      preLoaderRoute: typeof AppCmsEnquiriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cms/gallery': {
      id: '/app/cms/gallery'
      path: '/cms/gallery'
      fullPath: '/app/cms/gallery'
      preLoaderRoute: typeof AppCmsGalleryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cms/services': {
      id: '/app/cms/services'
      path: '/cms/services'
      fullPath: '/app/cms/services'
      preLoaderRoute: typeof AppCmsServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cms/testimonials': {
      id: '/app/cms/testimonials'
      path: '/cms/testimonials'
      fullPath: '/app/cms/testimonials'
      preLoaderRoute: typeof AppCmsTestimonialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lab/orders': {
      id: '/app/lab/orders'
      path: '/lab/orders'
      fullPath: '/app/lab/orders'
      preLoaderRoute: typeof AppLabOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lab/reports': {
      id: '/app/lab/reports'
      path: '/lab/reports'
      fullPath: '/app/lab/reports'
      preLoaderRoute: typeof AppLabReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lab/results': {
      id: '/app/lab/results'
      path: '/lab/results'
      fullPath: '/app/lab/results'
      preLoaderRoute: typeof AppLabResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lab/tests': {
      id: '/app/lab/tests'
      path: '/lab/tests'
      fullPath: '/app/lab/tests'
      preLoaderRoute: typeof AppLabTestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org/branches': {
      id: '/app/org/branches'
      path: '/org/branches'
      fullPath: '/app/org/branches'
      preLoaderRoute: typeof AppOrgBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org/modules': {
      id: '/app/org/modules'
      path: '/org/modules'
      fullPath: '/app/org/modules'
      preLoaderRoute: typeof AppOrgModulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org/roles': {
      id: '/app/org/roles'
      path: '/org/roles'
      fullPath: '/app/org/roles'
      preLoaderRoute: typeof AppOrgRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org/settings': {
      id: '/app/org/settings'
      path: '/org/settings'
      fullPath: '/app/org/settings'
      preLoaderRoute: typeof AppOrgSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org/users': {
      id: '/app/org/users'
      path: '/org/users'
      fullPath: '/app/org/users'
      preLoaderRoute: typeof AppOrgUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patient/book': {
      id: '/app/patient/book'
      path: '/patient/book'
      fullPath: '/app/patient/book'
      preLoaderRoute: typeof AppPatientBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pharmacy/dispensing': {
      id: '/app/pharmacy/dispensing'
      path: '/pharmacy/dispensing'
      fullPath: '/app/pharmacy/dispensing'
      preLoaderRoute: typeof AppPharmacyDispensingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pharmacy/medicines': {
      id: '/app/pharmacy/medicines'
      path: '/pharmacy/medicines'
      fullPath: '/app/pharmacy/medicines'
      preLoaderRoute: typeof AppPharmacyMedicinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pharmacy/purchases': {
      id: '/app/pharmacy/purchases'
      path: '/pharmacy/purchases'
      fullPath: '/app/pharmacy/purchases'
      preLoaderRoute: typeof AppPharmacyPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pharmacy/returns': {
      id: '/app/pharmacy/returns'
      path: '/pharmacy/returns'
      fullPath: '/app/pharmacy/returns'
      preLoaderRoute: typeof AppPharmacyReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pharmacy/sales': {
      id: '/app/pharmacy/sales'
      path: '/pharmacy/sales'
      fullPath: '/app/pharmacy/sales'
      preLoaderRoute: typeof AppPharmacySalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pharmacy/stock': {
      id: '/app/pharmacy/stock'
      path: '/pharmacy/stock'
      fullPath: '/app/pharmacy/stock'
      preLoaderRoute: typeof AppPharmacyStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pharmacy/suppliers': {
      id: '/app/pharmacy/suppliers'
      path: '/pharmacy/suppliers'
      fullPath: '/app/pharmacy/suppliers'
      preLoaderRoute: typeof AppPharmacySuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/site/$slug/blog/$blogSlug': {
      id: '/site/$slug/blog/$blogSlug'
      path: '/blog/$blogSlug'
      fullPath: '/site/$slug/blog/$blogSlug'
      preLoaderRoute: typeof SiteSlugBlogBlogSlugRouteImport
      parentRoute: typeof SiteSlugRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBillingInvoicesRoute: typeof AppBillingInvoicesRoute
  AppClinicAppointmentsRoute: typeof AppClinicAppointmentsRoute
  AppClinicConsultationsRoute: typeof AppClinicConsultationsRoute
  AppClinicDoctorsRoute: typeof AppClinicDoctorsRoute
  AppClinicPatientsRoute: typeof AppClinicPatientsRoute
  AppCmsBlogsRoute: typeof AppCmsBlogsRoute
  AppCmsBrandingRoute: typeof AppCmsBrandingRoute
  AppCmsEnquiriesRoute: typeof AppCmsEnquiriesRoute
  AppCmsGalleryRoute: typeof AppCmsGalleryRoute
  AppCmsServicesRoute: typeof AppCmsServicesRoute
  AppCmsTestimonialsRoute: typeof AppCmsTestimonialsRoute
  AppLabOrdersRoute: typeof AppLabOrdersRoute
  AppLabReportsRoute: typeof AppLabReportsRoute
  AppLabResultsRoute: typeof AppLabResultsRoute
  AppLabTestsRoute: typeof AppLabTestsRoute
  AppOrgBranchesRoute: typeof AppOrgBranchesRoute
  AppOrgModulesRoute: typeof AppOrgModulesRoute
  AppOrgRolesRoute: typeof AppOrgRolesRoute
  AppOrgSettingsRoute: typeof AppOrgSettingsRoute
  AppOrgUsersRoute: typeof AppOrgUsersRoute
  AppPatientBookRoute: typeof AppPatientBookRoute
  AppPharmacyDispensingRoute: typeof AppPharmacyDispensingRoute
  AppPharmacyMedicinesRoute: typeof AppPharmacyMedicinesRoute
  AppPharmacyPurchasesRoute: typeof AppPharmacyPurchasesRoute
  AppPharmacyReturnsRoute: typeof AppPharmacyReturnsRoute
  AppPharmacySalesRoute: typeof AppPharmacySalesRoute
  AppPharmacyStockRoute: typeof AppPharmacyStockRoute
  AppPharmacySuppliersRoute: typeof AppPharmacySuppliersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppIndexRoute: AppIndexRoute,
  AppBillingInvoicesRoute: AppBillingInvoicesRoute,
  AppClinicAppointmentsRoute: AppClinicAppointmentsRoute,
  AppClinicConsultationsRoute: AppClinicConsultationsRoute,
  AppClinicDoctorsRoute: AppClinicDoctorsRoute,
  AppClinicPatientsRoute: AppClinicPatientsRoute,
  AppCmsBlogsRoute: AppCmsBlogsRoute,
  AppCmsBrandingRoute: AppCmsBrandingRoute,
  AppCmsEnquiriesRoute: AppCmsEnquiriesRoute,
  AppCmsGalleryRoute: AppCmsGalleryRoute,
  AppCmsServicesRoute: AppCmsServicesRoute,
  AppCmsTestimonialsRoute: AppCmsTestimonialsRoute,
  AppLabOrdersRoute: AppLabOrdersRoute,
  AppLabReportsRoute: AppLabReportsRoute,
  AppLabResultsRoute: AppLabResultsRoute,
  AppLabTestsRoute: AppLabTestsRoute,
  AppOrgBranchesRoute: AppOrgBranchesRoute,
  AppOrgModulesRoute: AppOrgModulesRoute,
  AppOrgRolesRoute: AppOrgRolesRoute,
  AppOrgSettingsRoute: AppOrgSettingsRoute,
  AppOrgUsersRoute: AppOrgUsersRoute,
  AppPatientBookRoute: AppPatientBookRoute,
  AppPharmacyDispensingRoute: AppPharmacyDispensingRoute,
  AppPharmacyMedicinesRoute: AppPharmacyMedicinesRoute,
  AppPharmacyPurchasesRoute: AppPharmacyPurchasesRoute,
  AppPharmacyReturnsRoute: AppPharmacyReturnsRoute,
  AppPharmacySalesRoute: AppPharmacySalesRoute,
  AppPharmacyStockRoute: AppPharmacyStockRoute,
  AppPharmacySuppliersRoute: AppPharmacySuppliersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SiteSlugRouteChildren {
  SiteSlugBlogBlogSlugRoute: typeof SiteSlugBlogBlogSlugRoute
}

const SiteSlugRouteChildren: SiteSlugRouteChildren = {
  SiteSlugBlogBlogSlugRoute: SiteSlugBlogBlogSlugRoute,
}

const SiteSlugRouteWithChildren = SiteSlugRoute._addFileChildren(
  SiteSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AppRoute: AppRouteWithChildren,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FreeTrialRoute: FreeTrialRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RequestDemoRoute: RequestDemoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SolutionsRoute: SolutionsRoute,
  TestimonialsRoute: TestimonialsRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  SiteSlugRoute: SiteSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
