/** Curated, searchable icon names for admin "pick an icon" fields (content cards, team
 * members, etc.) — a sensible subset of lucide-react rather than its full ~1500-icon
 * library, so the picker stays fast and every option is one a real admin would want. */
export const ICON_OPTIONS: string[] = [
  // Medical / healthcare
  "Stethoscope",
  "HeartPulse",
  "Pill",
  "FlaskConical",
  "Syringe",
  "Activity",
  "Thermometer",
  "Bandage",
  "Ambulance",
  "Cross",
  "ClipboardList",
  "ClipboardCheck",
  "ClipboardPlus",
  "Microscope",
  "Hospital",
  "BriefcaseMedical",
  "Bone",
  "Brain",
  "Ear",
  "Baby",
  "Dna",
  // People / team
  "Users",
  "UsersRound",
  "UserCog",
  "UserPlus",
  "UserCheck",
  "User",
  "Handshake",
  "GraduationCap",
  "Award",
  "Trophy",
  // Business / SaaS
  "Building2",
  "Building",
  "Briefcase",
  "ShieldCheck",
  "ShieldAlert",
  "Target",
  "TrendingUp",
  "TrendingDown",
  "BarChart3",
  "PieChart",
  "LineChart",
  "Gauge",
  "Layers",
  "Layers3",
  "Blocks",
  "Puzzle",
  "Network",
  "Share2",
  "Link2",
  "Workflow",
  "Route",
  // Money / commerce
  "CreditCard",
  "Receipt",
  "Wallet",
  "DollarSign",
  "IndianRupee",
  "Percent",
  "TicketPercent",
  "Gift",
  "ShoppingCart",
  "Package",
  "Boxes",
  "Truck",
  "Warehouse",
  "Store",
  "Tag",
  "Scale",
  // Communication
  "Globe",
  "MapPin",
  "Phone",
  "Mail",
  "MessageSquare",
  "MessageCircle",
  "Bell",
  "Headphones",
  "Video",
  "Mic",
  // Time / schedule
  "Calendar",
  "CalendarCheck",
  "Clock",
  "Timer",
  "Hourglass",
  "History",
  "RefreshCw",
  // Status / feedback
  "CheckCircle2",
  "AlertTriangle",
  "Info",
  "HelpCircle",
  "LifeBuoy",
  "ThumbsUp",
  "Heart",
  "Smile",
  "Star",
  "Sparkles",
  "Flag",
  // Security
  "Lock",
  "KeyRound",
  "Fingerprint",
  "Eye",
  // Tech
  "Database",
  "Server",
  "Cloud",
  "Wifi",
  "Smartphone",
  "Laptop",
  "Monitor",
  "Code2",
  "Terminal",
  "GitBranch",
  "Cog",
  "Settings",
  "Wrench",
  "Zap",
  "Rocket",
  // Navigation / layout
  "LayoutGrid",
  "LayoutDashboard",
  "Compass",
  "Map",
  "Navigation",
  "ArrowRightCircle",
  "MoveRight",
  // Documents
  "FileText",
  "FileCheck",
  "ScrollText",
  "BookOpen",
  "Lightbulb",
  // Search / filter
  "Search",
  "Filter",
  // Media
  "Camera",
  "Image",
  "Palette",
  "Paintbrush",
  // Nature (occasionally used for wellness/values cards)
  "Leaf",
  "TreePine",
  "Droplet",
  "Sun",
  "Sunrise",
].sort();
